# Generated by Django 5.0.1 on 2024-03-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_post_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='raw_date',
        ),
    ]
