# Generated by Django 5.0.1 on 2024-03-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_date_comment_raw_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='raw_date',
            new_name='date',
        ),
    ]
