# Generated by Django 5.0.1 on 2024-03-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_raw_date_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='raw_date',
        ),
    ]
