# Generated by Django 5.0.1 on 2025-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pieces',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
